#!/usr/bin/env node
// Compiles apps/api/src/llm/skills/*.zh.md into skills/_compiled.ts.
// Run via `npm run skills:build` or it auto-runs before dev/test/build.
//
// .md files are the source of truth; _compiled.ts is generated and committed
// so wrangler/Workers/vitest can import string constants without any loader
// configuration.

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const skillsDir = join(here, '..', 'src', 'llm', 'skills');

function constName(filename) {
  return filename
    .replace(/\.zh\.md$/, '')
    .replace(/-/g, '_')
    .toUpperCase();
}

const entries = readdirSync(skillsDir)
  .filter((f) => f.endsWith('.zh.md'))
  .sort()
  .map((file) => ({
    file,
    name: constName(file),
    content: readFileSync(join(skillsDir, file), 'utf8'),
  }));

if (entries.length === 0) {
  console.error(`[skills:build] no *.zh.md files under ${skillsDir}`);
  process.exit(1);
}

const banner = [
  '// AUTO-GENERATED by apps/api/scripts/build-skills.mjs from skills/*.zh.md',
  '// DO NOT EDIT BY HAND. Run `npm run skills:build` after changing .md files.',
  '',
].join('\n');

const body = entries
  .map((e) => `export const ${e.name} = ${JSON.stringify(e.content)};`)
  .join('\n\n');

const antiSlop = entries.find((e) => e.name === 'ANTI_SLOP')?.content ?? '';
const slopWords = extractSlopWords(antiSlop);
const slopExports = `export const SLOP_WORDS: readonly string[] = ${JSON.stringify(slopWords, null, 2)};`;

const out = banner + '\n' + body + '\n\n' + slopExports + '\n';
const target = join(skillsDir, '_compiled.ts');
writeFileSync(target, out);

function extractSlopWords(markdown) {
  const sections = ['A', 'B'];
  const words = new Set();
  for (const section of sections) {
    const re = new RegExp(`## ${section}\\.[^\\n]*\\n+([\\s\\S]+?)(?=\\n## |$)`);
    const match = markdown.match(re);
    if (!match) continue;
    const lines = match[1]
      .split('\n')
      .map((l) => l.trim())
      .filter(Boolean);
    // 取所有含「、」的行，每行按顿号/逗号分词
    for (const line of lines) {
      if (!line.includes('、')) continue;
      for (const part of line.split(/[、，,]/)) {
        const w = part.trim();
        if (w && w.length <= 8) words.add(w);
      }
    }
  }
  return [...words].sort();
}

console.log(
  `[skills:build] wrote ${entries.length} skills → ${target.replace(process.cwd() + '/', '')}`,
);
for (const e of entries) console.log(`  - ${e.file} → ${e.name}`);
