import { and, eq } from 'drizzle-orm';
import type { Db } from '../db/client.js';
import { cardImages, cards, changeLogs } from '../db/schema.js';
import type { CardImageRow } from '../db/schema.js';

// Minimum R2 surface we use; Workers' R2Bucket type is generated by `wrangler types`.
export type R2PutBucket = {
  put(
    key: string,
    body: ReadableStream | ArrayBuffer | ArrayBufferView | Blob | string,
    options?: { httpMetadata?: { contentType?: string } },
  ): Promise<unknown>;
};

export type StoreImageInput = {
  bucket: R2PutBucket;
  db: Db;
  cardId: string;
  genJobId: string;
  projectId: string;
  b64: string;
  fullPrompt: string;
};

export function buildR2Key(genJobId: string, cardId: string, version: number): string {
  return `card-images/${genJobId}/${cardId}-v${version}.png`;
}

/**
 * Store generated image: upload PNG bytes to R2, insert CardImage row,
 * bump card.imageVersionId, and append ChangeLog. Returns the row.
 *
 * Idempotent on retry: the (card_id, gen_job_id, version) unique index lets a
 * second invocation no-op the row insert. R2 put is naturally idempotent (same
 * key → overwrite). The cards.imageVersionId update and changeLog insert run
 * only on first success to avoid duplicate audit entries.
 *
 * R2 url field stores the *r2 key* (e.g. `card-images/<job>/<card>-v1.png`),
 * not a full URL — the Worker proxy or CDN resolves it.
 */
export async function storeCardImage(input: StoreImageInput): Promise<CardImageRow> {
  const version = 1;
  const key = buildR2Key(input.genJobId, input.cardId, version);

  const bytes = base64ToBytes(input.b64);
  await input.bucket.put(key, bytes, {
    httpMetadata: { contentType: 'image/png' },
  });

  const inserted = await input.db
    .insert(cardImages)
    .values({
      cardId: input.cardId,
      genJobId: input.genJobId,
      version,
      url: key,
      fullPrompt: input.fullPrompt,
    })
    .onConflictDoNothing({
      target: [cardImages.cardId, cardImages.genJobId, cardImages.version],
    })
    .returning();

  if (inserted.length === 0) {
    // Retry path — row already exists, return it without re-running side effects.
    const [existing] = await input.db
      .select()
      .from(cardImages)
      .where(
        and(
          eq(cardImages.cardId, input.cardId),
          eq(cardImages.genJobId, input.genJobId),
          eq(cardImages.version, version),
        ),
      );
    return existing;
  }

  const imageRow = inserted[0];
  await input.db.update(cards).set({ imageVersionId: imageRow.id }).where(eq(cards.id, input.cardId));

  await input.db.insert(changeLogs).values({
    projectId: input.projectId,
    actor: 'agent',
    target: 'image',
    targetId: imageRow.id,
    action: 'create_card_image',
    before: null,
    after: imageRow,
  });

  return imageRow;
}

function base64ToBytes(b64: string): Uint8Array {
  const binary = atob(b64);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) out[i] = binary.charCodeAt(i);
  return out;
}
