import { eq } from 'drizzle-orm';
import type { Db } from '../db/client.js';
import { cardImages, cards, changeLogs } from '../db/schema.js';
import type { CardImageRow } from '../db/schema.js';

// Minimum R2 surface we use; Workers' R2Bucket type is generated by `wrangler types`.
export type R2PutBucket = {
  put(
    key: string,
    body: ReadableStream | ArrayBuffer | ArrayBufferView | Blob | string,
    options?: { httpMetadata?: { contentType?: string } },
  ): Promise<unknown>;
};

export type StoreImageInput = {
  bucket: R2PutBucket;
  db: Db;
  cardId: string;
  genJobId: string;
  projectId: string;
  b64: string;
  fullPrompt: string;
};

export function buildR2Key(genJobId: string, cardId: string, version: number): string {
  return `card-images/${genJobId}/${cardId}-v${version}.png`;
}

/**
 * Store generated image: upload PNG bytes to R2, insert CardImage row,
 * also bump the card's imageVersionId so the editor can swap to the new version,
 * and append a ChangeLog entry. Returns the inserted CardImage row.
 *
 * Note: R2 url field stores the *r2 key* (e.g. `card-images/<job>/<card>-v1.png`),
 * not a full URL. The Worker exposes a `/images/:key+` proxy or a CDN domain
 * resolves the key — both deferred. Frontend prepends API_BASE/images/.
 */
export async function storeCardImage(input: StoreImageInput): Promise<CardImageRow> {
  const version = 1;
  const key = buildR2Key(input.genJobId, input.cardId, version);

  const bytes = base64ToBytes(input.b64);
  await input.bucket.put(key, bytes, {
    httpMetadata: { contentType: 'image/png' },
  });

  const [imageRow] = await input.db
    .insert(cardImages)
    .values({
      cardId: input.cardId,
      genJobId: input.genJobId,
      version,
      url: key,
      fullPrompt: input.fullPrompt,
    })
    .returning();

  await input.db.update(cards).set({ imageVersionId: imageRow.id }).where(eq(cards.id, input.cardId));

  await input.db.insert(changeLogs).values({
    projectId: input.projectId,
    actor: 'agent',
    target: 'image',
    targetId: imageRow.id,
    action: 'create_card_image',
    before: null,
    after: imageRow,
  });

  return imageRow;
}

function base64ToBytes(b64: string): Uint8Array {
  const binary = atob(b64);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) out[i] = binary.charCodeAt(i);
  return out;
}
